server.port=8080

spring.application.name=bank management

spring.jpa.hibernate.ddl-auto=create

# Hibernate dialect (MySQL8Dialect for MySQL 8, MySQL5Dialect for older versions)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.data.jpa.repositories.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/bank_system
spring.datasource.username=root
spring.datasource.password=hr
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# CHANGE THIS in production use a 256-bit base64-encoded secret
app.jwt.secret=aurumbank_super_secret_key_change_in_production_min32chars!!
app.jwt.expiration-ms=86400000

#  AES Encryption Key (for sensitive field encryption)
# Must be exactly 16, 24 or 32 characters
app.encryption.key=AurumBank2024Key

# Logging
logging.level.com.aurumbank=INFO
