server.port=8080

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL (Production) uncomment to use
# spring.datasource.url=jdbc:postgresql://localhost:5432/MMCBank
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
# spring.datasource.password=yourpassword
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update


# CHANGE THIS in production use a 256-bit base64-encoded secret
app.jwt.secret=aurumbank_super_secret_key_change_in_production_min32chars!!
app.jwt.expiration-ms=86400000

#  AES Encryption Key (for sensitive field encryption)
# Must be exactly 16, 24 or 32 characters
app.encryption.key=AurumBank2024Key

# Logging
logging.level.com.aurumbank=INFO
